/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package repo_danielevir;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author HP
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp_Contextual = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        multiplicarImag = new javax.swing.JButton();
        sumarImag = new javax.swing.JButton();
        resltImag = new javax.swing.JButton();
        tf_Output = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_OpMate = new javax.swing.JTree();
        Bttn_ExpTXT = new javax.swing.JButton();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        pp_Contextual.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora de Imaginarios");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        multiplicarImag.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        multiplicarImag.setText("*");
        multiplicarImag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarImagActionPerformed(evt);
            }
        });

        sumarImag.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        sumarImag.setText("+");
        sumarImag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarImagActionPerformed(evt);
            }
        });

        resltImag.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        resltImag.setText("=");
        resltImag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resltImagActionPerformed(evt);
            }
        });

        try {
            tf_Output.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##+##i)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_Output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Output.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resltImag, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicarImag, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(sumarImag, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multiplicarImag, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resltImag, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(sumarImag, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Historial");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Operaciones Matematicas");
        jt_OpMate.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_OpMate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_OpMateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_OpMate);

        Bttn_ExpTXT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Bttn_ExpTXT.setText("Exportar Operaciones a Archivo de Texto");
        Bttn_ExpTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn_ExpTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(Bttn_ExpTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bttn_ExpTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bttn_ExpTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn_ExpTXTActionPerformed
        JFileChooser jfc = new JFileChooser();
        int tabueno = jfc.showSaveDialog(this);
        if (tabueno == JFileChooser.APPROVE_OPTION) {
            File archivo = jfc.getSelectedFile();
            try {
                FileWriter fw = null;
                BufferedWriter bw = null;
                Date fecha = new Date();
                try {
                    fw = new FileWriter(archivo, true);
                    bw = new BufferedWriter(fw);

                    for (String resultado : resultadossum) {
                        String[] sumas = resultado.split("\\+");
                        String num1Str = sumas[0];
                        String num2Str = sumas[1];
                        String operacion = "suma";
                        String totalStr = resultado.substring(resultado.indexOf("=") + 1);

                        String texto = num1Str + ", " + num2Str + ", " + operacion + ", " + totalStr;

                        bw.write(fecha + ", " + texto + "\n");
                    }

                    for (String resultado : resultadosmult) {
                        String[] multip = resultado.split("\\*"); // Change "\\+" to "\\*"
                        String num1Str = multip[0];
                        String num2Str = multip[1];
                        String operacion = "multiplicacion";
                        String totalStr = resultado.substring(resultado.indexOf("=") + 1);
                        String texto = num1Str + ", " + num2Str + ", " + operacion + ", " + totalStr;

                        bw.write(fecha + ", " + texto + "\n");
                    }

                    bw.flush();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(this, "Se agregó exitosamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error y no se agregó");
            }
        }


    }//GEN-LAST:event_Bttn_ExpTXTActionPerformed

    private void resltImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resltImagActionPerformed
        DefaultTreeModel modelo = new DefaultTreeModel(new DefaultMutableTreeNode("Operaciones Matematiacas"));
        //jt_OpMate.setModel(modelo);
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode sum = new DefaultMutableTreeNode("Suma");
        DefaultMutableTreeNode multis = new DefaultMutableTreeNode("Multiplicacion");
        raiz.add(sum);
        raiz.add(multis);

        if (!suma) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna operacion");
        }

        if (!mult) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna operacion");
        }

        if (suma) {

            NumImaginario num1 = numeros.get(0);
            NumImaginario num2 = numeros.get(1);
            NumImaginario sumas = num1.sumar(num2);
            suma = false;
            System.out.println(sumas);
            numeros.removeAll(numeros);
            String sumastr = "(" + num1 + ")" + "+" + "(" + num2 + ")" + "=" + "(" + sumas + ")";
            /* DefaultMutableTreeNode resltsum = new DefaultMutableTreeNode(sumastr);
            sum.add(resltsum);*/
            resultadossum.add(sumastr);
            System.out.println(sumastr);
        }

        if (mult) {
            NumImaginario num1 = numeros.get(0);
            NumImaginario num2 = numeros.get(1);
            NumImaginario multi = num1.multiplicar(num2);
            mult = false;
            System.out.println(multi);
            numeros.removeAll(numeros);
            String multistr = "(" + num1 + ")" + "*" + "(" + num2 + ")" + "=" + "(" + multi + ")";
            /*DefaultMutableTreeNode resltmulti = new DefaultMutableTreeNode(multistr);
            multis.add(resltmulti);*/
            resultadosmult.add(multistr);
            System.out.println(multistr);
        }
        for (String resultado : resultadossum) {
            DefaultMutableTreeNode resltsum = new DefaultMutableTreeNode(resultado);
            sum.add(resltsum);

        }

        for (String string : resultadosmult) {
            DefaultMutableTreeNode resltmulti = new DefaultMutableTreeNode(string);
            multis.add(resltmulti);
        }
        modelo.reload();
        jt_OpMate.setModel(modelo);
        tf_Output.setText("");
    }//GEN-LAST:event_resltImagActionPerformed

    private void sumarImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarImagActionPerformed
        try {
            double n1 = Double.parseDouble(tf_Output.getText().substring(1, 3));
            double n2 = Double.parseDouble(tf_Output.getText().substring(4, 6));
            NumImaginario imag1 = new NumImaginario(n1, n2);
            if (numeros.size() < 2) {
                numeros.add(imag1);
                numeros1.add(imag1);
                suma = true;
                tf_Output.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Ya ingresó 2 operaciones, proceda a la respuesta");
            }
            System.out.println(imag1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingresó un formato incorrecto\n"
                    + "En el caso de tener ingresar un numero menor a 10, ingresarlo así: 01");
        }
    }//GEN-LAST:event_sumarImagActionPerformed

    private void multiplicarImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarImagActionPerformed
        try {
            double n1 = Double.parseDouble(tf_Output.getText().substring(1, 3));
            double n2 = Double.parseDouble(tf_Output.getText().substring(4, 6));
            NumImaginario imag1 = new NumImaginario(n1, n2);
            if (numeros.size() < 2) {
                numeros.add(imag1);
                numeros1.add(imag1);
                mult = true;
                tf_Output.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Ya ingresó 2 operaciones, proceda a la respuesta");
            }
            System.out.println(imag1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingresó un formato incorrecto\n"
                    + "En el caso de tener ingresar un numero menor a 10, ingresarlo así: 01");
        }
    }//GEN-LAST:event_multiplicarImagActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_OpMate.getModel();
        TreePath camino = jt_OpMate.getSelectionPath();
        if (camino != null) {
            DefaultMutableTreeNode seleccionado = (DefaultMutableTreeNode) camino.getLastPathComponent();
            if (seleccionado != null && seleccionado.getParent() != null) {
                DefaultMutableTreeNode elpapa = (DefaultMutableTreeNode) seleccionado.getParent();
                String resultado = seleccionado.getUserObject().toString();
                elpapa.remove(seleccionado);
                modelo.reload(elpapa);
                for (int i = 0; i < resultadossum.size(); i++) {
                    if (resultadossum.get(i).equals(resultado)) {
                        resultadossum.remove(i);
                        break;
                    }
                }

                for (int i = 0; i < resultadosmult.size(); i++) {
                    if (resultadosmult.get(i).equals(resultado)) {
                        resultadosmult.remove(i);
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void jt_OpMateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_OpMateMouseClicked
        if (evt.isMetaDown()) {
            pp_Contextual.show(jt_OpMate, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_OpMateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private ArrayList<NumImaginario> numeros = new ArrayList();
    private ArrayList<NumImaginario> numeros1 = new ArrayList();
    private ArrayList<String> resultadossum = new ArrayList();
    private ArrayList<String> resultadosmult = new ArrayList();
    private ArrayList resultados = new ArrayList();
    private boolean suma = false;
    private boolean mult = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn_ExpTXT;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jt_OpMate;
    private javax.swing.JButton multiplicarImag;
    private javax.swing.JPopupMenu pp_Contextual;
    private javax.swing.JButton resltImag;
    private javax.swing.JButton sumarImag;
    private javax.swing.JFormattedTextField tf_Output;
    // End of variables declaration//GEN-END:variables
}
